- id: auto-commit-msg
  name: auto-commit-msg
  description: "Automatically generates commit messages based on diffs"
  entry: auto-commit-msg
  language: python
  require_serial: true
  additional_dependencies: ['openai==0.27.8']
