- id: auto-commit-msg
  name: auto-commit-msg
  description: "Automatically generates commit messages based on diffs"
  entry: auto-commit-msg.py
  language: python
  type: commit-msg
  require_serial: true
  additional_dependencies: ['openai==0.27.8']
  minimum_pre_commit_version: 2.9.2
  